from tkinter import *


root = Tk()
root.title("CIK Academy")
root.iconbitmap("cik.ico")
root.geometry("350x350")

# f = ("Arial", 18, "bold")
# u1 = Label(root, text="Konstitusiya", font=f, bg="red")
# u2 = Label(root, text="Kuba", font=f, bg="red")
# u3 = Label(root, text="Avstraliya\nKolumbiya", font=f, bg="red")
# # u1.pack()
# # u2.pack()
# # u3.pack()
# u1.grid(row=2, column=1)
# u2.grid(row=0, column=0)
# u3.grid(row=1, column=2)

# f = ("Arial", 26, "bold")
# u0 = Label(root, text="0", font=f, relief=RAISED, width=9, padx=7)
# u1 = Label(root, text="1", font=f, relief=RAISED, width=3)
# u2 = Label(root, text="2", font=f, relief=RAISED, width=3)
# u3 = Label(root, text="3", font=f, relief=RAISED, width=3)
# u4 = Label(root, text="4", font=f, relief=RAISED, width=3)
# u5 = Label(root, text="5", font=f, relief=RAISED, width=3)
# u6 = Label(root, text="6", font=f, relief=RAISED, width=3)
# u7 = Label(root, text="7", font=f, relief=RAISED, width=3)
# u8 = Label(root, text="8", font=f, relief=RAISED, width=3)
# u9 = Label(root, text="9", font=f, relief=RAISED, width=3)
# u0.grid(row=3, column=0, columnspan=3)
# u1.grid(row=2, column=0)
# u2.grid(row=2, column=1)
# u3.grid(row=2, column=2)
# u4.grid(row=1, column=0)
# u5.grid(row=1, column=1)
# u6.grid(row=1, column=2)
# u7.grid(row=0, column=0)
# u8.grid(row=0, column=1)
# u9.grid(row=0, column=2)

root.mainloop()
